name: Gradle Build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Build and package
        run: |
          chmod +x gradlew
          ./gradlew
          ./gradlew packagePlugin
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::$(./gradlew -q printVersion)
      - name: Copy file to release
        run: |
          mkdir -p ${{ github.workspace }}/release
          cp examplePages/Wave-Link-Example.tpz ${{ github.workspace }}/release
          cp examplePages/Wave-Link-Output-Monitor.tpz ${{ github.workspace }}/release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.VERSION }}
          release_name: Release ${{ steps.get_version.outputs.VERSION }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/plugin/WaveLinkPlugin.tpp
          asset_name: WaveLinkPlugin.tpp
          asset_content_type: application/octet-stream
      - name: Upload file to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/release/Wave-Link-Example.tpz
          asset_name: Wave-Link-Example.tpz
          asset_content_type: application/octet-stream
      - name: Upload file to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/release/Wave-Link-Output-Monitor.tpz
          asset_name: Wave-Link-Output-Monitor.tpz
          asset_content_type: application/octet-stream

